#!/usr/bin/env python3
"""Git-based snapshot management for dream safety.

Provides atomic save/restore of .wiki/ state via an internal git repository.
The .wiki/.git repo is independent of the parent project — .wiki is typically
gitignored, so dream commits never pollute the main history.

Usage:
    from _snapshot import ensure_git_repo, create_snapshot, rollback

    ensure_git_repo(wiki_dir)
    commit_hash = create_snapshot(wiki_dir, "pre-phase3-merge")
    # ... modify pages ...
    if disaster:
        rollback(wiki_dir, commit_hash, "phase3-quality-degraded")
"""

from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def _git_available() -> bool:
    """Check whether git is installed and usable."""
    try:
        subprocess.run(
            ["git", "--version"],
            capture_output=True,
            check=True,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def ensure_git_repo(wiki_dir: Path) -> bool:
    """Ensure *wiki_dir* is a git repository.  Initialises one if missing.

    Returns True when git is available and the directory is a repo (or was
    successfully initialised).  Returns False when git is not installed.
    """
    if not _git_available():
        print("  [dream/snapshot] git not available — snapshots disabled",
              file=sys.stderr)
        return False

    git_dir = wiki_dir / ".git"
    if git_dir.is_dir():
        return True

    wiki_dir.mkdir(parents=True, exist_ok=True)
    try:
        subprocess.run(
            ["git", "-C", str(wiki_dir), "init"],
            capture_output=True,
            check=True,
        )
        gitignore = wiki_dir / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(
                "# Auto-generated by llm-wiki-skill dream\n"
                "dream/*.out.log\n"
                "dream/*.err.log\n"
                "__pycache__/\n"
                "*.pyc\n"
            )
        print("  [dream/snapshot] initialised git repo in .wiki/", file=sys.stderr)
        return True
    except subprocess.CalledProcessError as exc:
        print(f"  [dream/snapshot] git init failed: {exc}", file=sys.stderr)
        return False


def create_snapshot(wiki_dir: Path, label: str) -> str | None:
    """Stage all .wiki changes and commit with ``dream: {label}``.

    Returns the commit hash (str) on success, or None when git is unavailable
    or there is nothing to commit.
    """
    if not _git_available():
        return None

    git_dir = wiki_dir / ".git"
    if not git_dir.is_dir():
        ensured = ensure_git_repo(wiki_dir)
        if not ensured:
            return None

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    message = f"dream: {label} [{timestamp}]"

    try:
        subprocess.run(
            ["git", "-C", str(wiki_dir), "add", "-A"],
            capture_output=True,
            check=True,
        )
        result = subprocess.run(
            ["git", "-C", str(wiki_dir), "commit", "--allow-empty",
             "-m", message],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(f"  [dream/snapshot] commit warning: {result.stderr.strip()}",
                  file=sys.stderr)

        log = subprocess.run(
            ["git", "-C", str(wiki_dir), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        commit_hash = log.stdout.strip()[:12]
        print(f"  [dream/snapshot] saved snapshot {commit_hash}: {label}",
              file=sys.stderr)
        return commit_hash
    except subprocess.CalledProcessError as exc:
        print(f"  [dream/snapshot] snapshot failed: {exc}", file=sys.stderr)
        return None


def rollback(wiki_dir: Path, commit_hash: str, label: str = "") -> bool:
    """Restore .wiki working tree to *commit_hash*.

    Uses ``git checkout <hash> -- .`` which preserves the git history while
    reverting file contents.  A new commit records the rollback so the
    timeline is never lost.

    Returns True on success.
    """
    if not _git_available():
        print("  [dream/snapshot] cannot rollback — git not available",
              file=sys.stderr)
        return False

    git_dir = wiki_dir / ".git"
    if not git_dir.is_dir():
        print("  [dream/snapshot] cannot rollback — .wiki is not a git repo",
              file=sys.stderr)
        return False

    try:
        subprocess.run(
            ["git", "-C", str(wiki_dir), "checkout", commit_hash, "--", "."],
            capture_output=True,
            check=True,
        )
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        rollback_msg = (
            f"dream: rollback to {commit_hash} [{label}]" if label
            else f"dream: rollback to {commit_hash} [{timestamp}]"
        )
        subprocess.run(
            ["git", "-C", str(wiki_dir), "add", "-A"],
            capture_output=True,
            check=True,
        )
        subprocess.run(
            ["git", "-C", str(wiki_dir), "commit", "--allow-empty",
             "-m", rollback_msg],
            capture_output=True,
        )
        print(f"  [dream/snapshot] rolled back to {commit_hash}: {label}",
              file=sys.stderr)
        return True
    except subprocess.CalledProcessError as exc:
        print(f"  [dream/snapshot] rollback failed: {exc}", file=sys.stderr)
        return False


def list_snapshots(wiki_dir: Path, limit: int = 20) -> list[dict]:
    """Return recent dream-related commits as a list of dicts.

    Each dict: ``{hash, date, message}``.
    """
    git_dir = wiki_dir / ".git"
    if not git_dir.is_dir():
        return []

    try:
        result = subprocess.run(
            ["git", "-C", str(wiki_dir), "log",
             "--grep=^dream:", "--format=%h|%aI|%s",
             f"-n{limit}"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            return []

        snapshots: list[dict] = []
        for line in result.stdout.strip().splitlines():
            if not line:
                continue
            parts = line.split("|", 2)
            if len(parts) == 3:
                snapshots.append({
                    "hash": parts[0],
                    "date": parts[1],
                    "message": parts[2],
                })
        return snapshots
    except subprocess.CalledProcessError:
        return []
