#!/usr/bin/env python3
"""crystallize.py — Session → Digest Pipeline for llm-wiki."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from config import get_wiki_dir

WIKI_DIR = get_wiki_dir()
PAGES_DIR = WIKI_DIR / "pages"
MEMORY_DIR = WIKI_DIR / "memory"
GRAPH_DIR = WIKI_DIR / "graph"
WORKING_FILE = os.path.join(MEMORY_DIR, "working.json")
ENTITIES_FILE = os.path.join(GRAPH_DIR, "entities.json")
EDGES_FILE = os.path.join(GRAPH_DIR, "edges.json")


def _load_json(path: str) -> dict | list:
    if not os.path.exists(path):
        return [] if 'working' in path or 'memory' in path else ({'edges': []} if 'edges' in path else {})
    try:
        with open(path, encoding='utf-8') as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return [] if 'working' in path else ({'edges': []} if 'edges' in path else {})


def _save_json(path: str, data) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False, default=str)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _slugify(name: str) -> str:
    return re.sub(r'[^a-z0-9-]', '', name.lower().replace(' ', '-').replace('_', '-'))


def _auto_digest(topic: str, date: str) -> str | None:
    """Create a minimal auto-digest without a session file (for hook use).

    Returns digest path, or None if wiki is not initialized.
    """
    if not os.path.isdir(PAGES_DIR):
        return None

    slug = _slugify(topic)
    digest_id = f'session-{date}-{slug}'
    now = _now()

    digest = f"""---
type: Session Digest
title: Session Digest — {date} — {topic}
description: Auto-crystallized knowledge from the {topic} session.
tags: [session, crystallized]
timestamp: {now}
topic: {topic}
entities: []
quality_score: 0.5
confidence: 0.4
scope: private
---

# Session Digest — {date} — {topic}

## Summary

Auto-crystallized session from {now}. Topic: {topic}.

## Context

This digest was auto-generated by the session-end hook. No session
transcript was provided, so findings are empty. Review and add context manually
if this session contained valuable insights.

## Key Findings

- [ ] Review session and add key findings manually

## Open Questions

- [ ] What was accomplished in this session?

## Source Quality

- **Source type**: auto-crystallized (no transcript)
- **Verification needed**: All content needs manual review
"""

    sessions_dir = os.path.join(PAGES_DIR, "sessions")
    os.makedirs(sessions_dir, exist_ok=True)
    digest_path = os.path.join(sessions_dir, f'{digest_id}.md')
    with open(digest_path, 'w', encoding='utf-8') as f:
        f.write(digest)

    return digest_path


def on_memory_write(entity_id: str, claim: str, confidence: float) -> list[dict]:
    """Check for contradictions after writing to memory. Called as a hook.

    Returns list of contradictions found.
    """
    contradictions = check_contradictions([{
        'id': f'fact-{_slugify(claim[:30])}',
        'content': claim,
        'entity_id': entity_id,
        'confidence': confidence,
    }])
    if contradictions:
        msg = f'CONTRADICTION: {entity_id} — {claim[:60]}...'
        print(msg, file=sys.stderr)
    return contradictions


def create_digest(session_file: str, topic: str, date: str) -> str:
    """Create a session digest page from session content."""
    if not os.path.exists(session_file):
        raise FileNotFoundError(f"Session file not found: {session_file}")

    with open(session_file, encoding='utf-8') as f:
        content = f.read()

    slug = _slugify(topic)
    digest_id = f'session-{date}-{slug}'

    entities = []
    for match in re.finditer(r'\[\[([^\]]+)\]\]', content):
        target = match.group(1).split('|')[0].strip()
        if target:
            entities.append(target)

    findings = []
    for line in content.split('\n'):
        line = line.strip()
        if line.startswith('- ') and len(line) > 10:
            findings.append(line[2:].strip())

    digest = f"""---
type: Session Digest
title: Session Digest — {date} — {topic}
description: Crystallized knowledge from the {topic} session.
tags: [session, crystallized]
timestamp: {_now()}
topic: {topic}
entities: {json.dumps(entities[:10])}
quality_score: 0.7
confidence: 0.6
scope: private
---

# Session Digest — {date} — {topic}

## Summary

Session captured from {os.path.basename(session_file)}. Topic: {topic}.

## Context

Auto-crystallized from working session.

## Key Findings

"""
    for f in findings[:10]:
        digest += f'- {f}\n'

    digest += """
## Entities Discovered or Updated

"""
    for e in list(set(entities))[:10]:
        digest += f'| [{e}](/concepts/{_slugify(e)}.md) | unknown | identified | 0.5 |\n'

    if entities:
        digest = digest[:digest.rfind('\n')] + '\n'

    digest += """
## Open Questions

- [ ] Review and verify auto-extracted findings
- [ ] Add manual context and decisions

## Source Quality

- **Source type**: session transcript
- **Primary sources**: auto-extracted from conversation
- **Verification needed**: All claims need human review
"""

    sessions_dir = os.path.join(PAGES_DIR, "sessions")
    os.makedirs(sessions_dir, exist_ok=True)
    digest_path = os.path.join(sessions_dir, f'{digest_id}.md')
    with open(digest_path, 'w', encoding='utf-8') as f:
        f.write(digest)

    return digest_path


def extract_facts(digest_content: str) -> list[dict]:
    """Extract standalone facts from digest for working memory."""
    facts = []
    lines = digest_content.split('\n')
    in_findings = False

    for line in lines:
        if '## Key Findings' in line:
            in_findings = True
            continue
        if in_findings and line.startswith('##'):
            break
        if in_findings and line.startswith('- ') and len(line) > 5:
            claim = line[2:].strip()
            fact_id = f'fact-{_slugify(claim[:30])}'
            facts.append({
                'id': fact_id,
                'content': claim,
                'source': 'session-digest',
                'entity_ids': [],
                'timestamp': _now(),
                'confidence': 0.5,
            })

    return facts


def update_graph(entities: list[dict], edges: list[dict]):
    """Update entities.json and edges.json with session discoveries."""
    registry = _load_json(ENTITIES_FILE)
    if isinstance(registry, list):
        registry = {}
    for entity in entities:
        eid = entity.get('id', '')
        if eid and eid not in registry:
            registry[eid] = {
                'id': eid, 'type': entity.get('type', 'unknown'),
                'name': entity.get('name', eid),
                'attributes': entity.get('attributes', {}),
                'confidence': entity.get('confidence', 0.5),
                'sources': [entity.get('source', 'crystallize')],
                'page': f'pages/entities/{eid}.md',
            }
    _save_json(ENTITIES_FILE, registry)

    edges_data = _load_json(EDGES_FILE)
    all_edges = edges_data.get('edges', []) if isinstance(edges_data, dict) else []
    for edge in edges:
        edge['created_at'] = _now()
        all_edges.append(edge)
    _save_json(EDGES_FILE, {'edges': all_edges})


def check_contradictions(facts: list[dict]) -> list[dict]:
    """Compare new facts against existing knowledge for contradictions."""
    entities_data = _load_json(ENTITIES_FILE)
    if not isinstance(entities_data, dict):
        return []

    contradictions = []
    for fact in facts:
        claim = fact.get('content') or fact.get('claim') or ''
        for eid, entity in entities_data.items():
            name = entity.get('name', '')
            if name and name.lower() in claim.lower():
                existing_conf = entity.get('confidence', 0)
                new_conf = fact.get('confidence', 0)
                if abs(existing_conf - new_conf) > 0.4:
                    contradictions.append({
                        'fact_id': fact.get('id'),
                        'existing_entity': eid,
                        'existing_confidence': existing_conf,
                        'new_confidence': new_conf,
                        'claim': claim[:80],
                    })
    return contradictions


def _main() -> None:
    parser = argparse.ArgumentParser(description='llm-wiki Session Crystallization')
    parser.add_argument('--session-file', help='Path to session transcript')
    parser.add_argument('--topic', help='Session topic')
    parser.add_argument('--date', help='Session date (default: today)')
    parser.add_argument('--auto', action='store_true', help='Run without interaction')
    args = parser.parse_args()

    date = args.date or datetime.now(timezone.utc).strftime('%Y-%m-%d')

    if args.auto and not args.session_file:
        auto_topic = args.topic or f'auto-session-{date}'
        digest_path = _auto_digest(auto_topic, date)
        if digest_path is None:
            print(json.dumps({'status': 'skipped', 'reason': 'No wiki initialized'}, indent=2))
            return
        with open(digest_path, encoding='utf-8') as f:
            digest_content = f.read()
    elif args.session_file:
        if not args.topic:
            parser.error('--topic is required when --session-file is provided')
            sys.exit(1)
        digest_path = create_digest(args.session_file, args.topic, date)
        with open(digest_path, encoding='utf-8') as f:
            digest_content = f.read()
    else:
        parser.print_help()
        sys.exit(1)

    facts = extract_facts(digest_content)

    working = _load_json(WORKING_FILE)
    if not isinstance(working, list):
        working = []
    working.extend(facts)
    _save_json(WORKING_FILE, working)

    contradictions = check_contradictions(facts)

    output = {
        'digest_path': digest_path,
        'facts_extracted': len(facts),
        'working_memory_size': len(working),
        'contradictions_found': len(contradictions),
    }
    if contradictions:
        output['contradiction_details'] = contradictions

    print(json.dumps(output, indent=2, ensure_ascii=False, default=str))


if __name__ == "__main__":
    _main()
